### ISSUE TITLE
How to do ES6 import/export correctly?

### ISSUE THREAD

**Issue by BillyZac** [thlorenz/proxyquire#169]
[See this](https://github.com/BillyZac/proxyquire-question) for a reproduction of the issue.

The module I want to test exports using ES 6 export default. In order to make it work, I have to add .default in the proxyquire call. (See fetchBuilds.test.js.) This seems not quite right.

Let me know if more info is needed. Any help is much appreciated!

**Comment by bendrucker** [comment]
So `import`/`export` aren't really a thing, just something Babel makes up. So yeah, you'll have to add that `.default` because proxyquire isn't aware of the module hackery going on behind the scenes. Babel's really doing the same thing for you if you look at the runnable output.

I recommend strongly against the use of those keywords in any Node modules for exactly this reason. You're relying on third party shims for semantics.

**Comment by BillyZac** [comment]
Okay, many thanks for taking the time to let me know.
