### ISSUE TITLE
Mocking URLs

### ISSUE THREAD

**Issue by Wildhoney** [thlorenz/proxyquire#227]
I'm trying to mock URL imports:

```javascript
proxyquire(
  'https://cdn.jsdelivr.net/npm/promisesque@2.0.0/src/index.js',
  require('promisesque')
);
```

But I receive a bunch of:

> Error: Cannot find module 'https://cdn.jsdelivr.net/npm/promisesque@2.0.0/src/index.js'

Is it not supported?

**Comment by bendrucker** [comment]
You definitely can't `require('https://...')` so proxyquire doesn't support that either

**Comment by Wildhoney** [comment]
You can in the browser.

However when running tests they're run in Node, which obviously don't support `http`/`https` &mdash; my idea was to mock those imports for the test environment.

**Comment by Wildhoney** [comment]
It should call the original module, because I've listed it as a dependency. Although I realise `import !== require`, `proxyquire` mocks `import`s just fine.

Requiring URLs is perfectly valid outside of Node with `<script type="module" />`. I figured it would be in the remit of `proxyquire` to be able to replace a URL import with its local dependency.

**Comment by bendrucker** [comment]
Proxyquire does not support `import` keywords, except when statically transformed into `require` calls such that they are no longer imports. It is 100% focused on supporting the valid methods of loading a module in the current Node release. At present, that is exclusively `require`. "Requiring URLs" is not a thing because Node is the canonical implementation of `require` and it's never done that. 

I've made my case for acknowledging Node's module behavior instead of hacking around it. If you need to make proxyquire work with invalid modules, use `noCallThru`. We only recommend that for stubbing a module that's missing during tests as opposed to one that _must_ be stubbed because it's invalid in all circumstances. But it should work.

**Comment by Wildhoney** [comment]
Thanks.

Is the below code right? As I still receive the same:

> Error: Cannot find module 'https://cdn.jsdelivr.net/npm/promisesque@2.0.0/src/index.js'

```javascript
const proxyquire = require('proxyquire');

proxyquire.noCallThru();

proxyquire(
    'https://cdn.jsdelivr.net/npm/promisesque@2.0.0/src/index.js',
    require('promisesque')
);
```

**Comment by bendrucker** [comment]
The first arg should be the module under test. If you have the following it's typically a sign of something wrong:

```js
proxyquire(path, stubs)
```

proxyquire is a require drop-in with a second argument, so always:

```js
const myModule = proxquire(path, stubs)
```

Proxyquire does not want you mutating module state and then depending on those mutations later. It makes a new copy of your _module under test_ (i.e. your source code, not your deps) with the associated stubs so that normal/later `require` calls don't break from leaky mocks.

You're looking for something like:

```js
const myModule = proxyquire('./my-module-path', {
  'https://cdn.jsdelivr.net/npm/promisesque@2.0.0/src/index.js': require('promisesque')
})
```

But again, proxyquire is very much not meant for this purpose. Namely:

* Your module under test isn't valid and _must_ be mocked to run in Node
* The dependency (promisesque ) does not require mocking

You'd really be better off with something that will rewrite your require statements from the URL into plain `require('promisesque')` during transpilation. Doing the replacement dynamically at runtime is awkward and pollutes your test with "build instructions" which transpilation would typically handle.
