### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by nasht00** [thlorenz/proxyquire#231]
The modules I want to test and/or mock use some global variables.

For example, the source code of the module makes a reference to a variable `session`, which is not defined anywhere but is available at runtime.

Consider the module `globals.js`:

```
let globals = {
    contextName: "DATA_PIPELINE",
    reportContext: "report",
    session: session
};
 
module.exports = globals;
```

`session` is not defined in this file but available at runtime. It's a global variable of the environment (not under my control). When using proxyquire on such a module, I get `ReferenceError: session is not defined`. 

My goal is actually to mock the behavior of `session` in my tests, but I can't even load the module at all.

Any ideas?

**Comment by bendrucker** [comment]
Hi, you should use the `global` object to get/set user-defined global values for clarity. Proxyquire doesn't have any interaction with globals, including built-ins like `process`. If you want to modify their behavior before loading a module, you'd need to set the global variable, load the module, and then revert the change after the test runs.

```js
// get original
const { foo } = global

// load module and make assertions
const bar = proxyquire('./bar', stubs)
assert(bar(), '...')

// re-set original
Object.assign(global, { foo })
```

Proxyquire is designed to help you create test isolation at the module level. Since globals are by definition are scoped to the whole process instead of a module, they fall outside its scope. It probably won't be possible to create a wrapper function around proxyquire to accomplish what I illustrated above. Depending on your code, you can't safely unset `global.foo` until you've finished your test (as opposed to after you load the module). Depends on how you access the properties (your original case might work) but in general it's not possible to make a `proxyquireWithGlobals` wrapper.

Hope that helps!
