### ISSUE TITLE
Problem with a simple example...

### ISSUE THREAD

**Issue by ScottChapman** [thlorenz/proxyquire#248]
So, newbie here... I'm trying a fairly simple example. My simple example is here:
https://github.com/ScottChapman/proxyquire-example

Any ideas what I am doing wrong there?

**Comment by bendrucker** [comment]
Would be helpful to see exactly what you expected versus what you got. What stands out to me is that your `MyClass.js` module exports a class, but then you proxyquire it in your test and invoke it without using `new` to instantiate a copy. I would expect this code to throw whether you use proxyquire or not. 

Happy to provide further help if that's not it but since this doesn't seem like a bug I'll go ahead and close.

**Comment by ScottChapman** [comment]
I was expecting the test function to use my mocked `fs` instance which returned some text for the contents of a file instead of access an actual file.

But you are right, creating an instance of the class and using that did actually work. Thanks for the help. I guess I have to go back to the original thing I was testing and see how that maps. Odd I missed that though
