### ISSUE TITLE
fail for non-existing path?

### ISSUE THREAD

**Issue by stephanos** [thlorenz/proxyquire#58]
When I stub a path that does not exist, no error is thrown (correct me if I'm wrong). To prevent confusion, It would be *very* helpful to not silently accept ineffective stubs.

**Comment by bendrucker** [comment]
Not sure if I'm understanding you correctly.

Given:
```js
proxyquire('./exists', {
  './does-not-exist': stub
})
```

Are you asking for `proxyquire` to throw here?

**Comment by stephanos** [comment]
Exactly.

But often it's more subtle, e.g. I rename a file and it's not found *anymore*, I miss a `.` at the beginning of relative files etc.

**Comment by bendrucker** [comment]
Okay. Unfortunately that's not possible. 

---

Node requires are dynamic and so even if we wanted to take on the burden of doing static analysis it doesn't work anyway:

**test.js**
```js
proxyquire('./exists', {
  './does-not-exist': stub
})
```

**exists.js**
```js
var prefix = './does-not-'
require(prefix + 'exist')
```

So the route of using [has-require](https://github.com/bendrucker/has-require) to see if that file contains `require('ben-does-not-exist') is out. 

---

A dynamic approach that tries to `require.resolve` the module first doesn't work either because [the following is valid and documented use case](https://github.com/thlorenz/proxyquire#using-proxyquire-to-simulate-the-absence-of-modules):

```js
try {
  require('package')
} catch (e) {
  require('fallback')
}

---

The real answer here is that it's not proxyquire's role to tell you when you have a mistake in both your stub definitions and your `require` calls. It's theoretically possible but would be a ton of effort. You should be writing integration tests that don't mock modules if your application is so large and complex that mistakes like this are frequently surfacing in production.

**Comment by stephanos** [comment]
Well, 99.9% of the time in *my* code base I do *not* use a dynamic or conditional `require`. I don't quite understand why there couldn't be a strict/validation mode just because there are a few edge cases.

Anyway, is there any way I can do the verification myself?

**Comment by thlorenz** [comment]
@stephanos You could totally write a proxyquire validator.
What it would do is parse the code, find all calls to proxyquire and reason about if the stubs are set up reference files that exist.

However if you don't use the `@noCallThru` option proxyquire will try to find the actual file and therefore should fail immediately if it doesn't exist.

If this is not so please supply a test that shows that issue and we can attempt to fix it.
