### ISSUE TITLE
Special handling for transpiled ES6 modules?

### ISSUE THREAD

**Issue by matthewwithanm** [thlorenz/proxyquire#64]
Currently, if you want to stub a transpiled es6 module, you need to do something like this:

```javascript
const mod = proxyquire('./path/to/mod', {
  '../dep': {
    __esModule: true,
    doSomething: function() { /* ... */ },
  },
});
```

The `__esModule` is used by tools like Babel and Traceur to deal with module format interop. It would be convenient if proxyquire automatically added it to the stub if present in the original.

**Comment by bendrucker** [comment]
Proxyquire is already supposed to do something to this effect generically. Unless you enable `noCallThru` mode globally or for a particular stub, proxyquire will copy properties that don't exist on the destination:

https://github.com/thlorenz/proxyquire/blob/02b257837b381cb162dddea1de541de7b2984143/lib/proxyquire.js#L11-L19

If you're not seeing that then it's a bug. Can you post a reproducible example?

**Comment by matthewwithanm** [comment]
`__esModule` is added using `Object.defineProperty` without the enumerable flag (at least with Babel), so `Object.keys` won't see it.

**Comment by bendrucker** [comment]
Right, totally forgot `enumerable` is false by default. Someone actually just reported a proxyquire*ify* bug with the same bit of code (thlorenz/proxyquireify#32). I'm going to pull out the fill-in code into its own module and I'll handle this there. 

This doesn't need to be a special case. Instead of copying the properties directly I'll just copy the descriptors. Getters and setters would then work normally as well.

**Comment by matthewwithanm** [comment]
👍Awesome, thanks!
