### ISSUE TITLE
Is it possible to assert that what I proxyquired was actually required?

### ISSUE THREAD

**Issue by arasmussen** [thlorenz/proxyquire#68]
```
// foo-test.js
var proxyquire = require('proxyquire');
var foo = proxyquire('../foo', {'../bar: {}});

assert(proxyquire.wasProxied('../bar'));
```

Can I do something along these lines in order to ensure that my ../bar path hasn't changed since I stubbed the file? This would be helpful for a constantly changing codebase in case the stubbed file moves and then is no longer stubbed.

**Comment by bendrucker** [comment]
No, that's not something proxyquire can/will do with the API specified. Even an events interface doesn't seem feasible. Proxyquire is a singleton and so the amount of info you'd have to spit out to actually try to do this check would be pretty substantial.

If you can come up with some ideas on how to implement this and ideally even play with a PR, we can definitely reconsider. Otherwise, the best approach in the mean time would be to write a wrapper and use static analysis (https://github.com/bendrucker/has-require) which will work equally well as long as you're not using dynamic requires.
