### ISSUE TITLE
A way to fake require.resolve function

### ISSUE THREAD

**Issue by gyandeeps** [thlorenz/proxyquire#77]
To start I want to say its an excellent module. Thanks for the great work.

Now I do use proxyquire to fake certain modules, that works great. But in my application i use the function `require.resolve` function to get the path of the dependency but I am not able to fake it.

Example code:
```js
function getPlugin(pluginName){
    var plugin = require(pluginName);
    var pluginPath = require.resolve(pluginName); // ---> Error here
    
    return {
        api: plugin,
        path: pluginPath
    };
}
```

Since I use proxyquire so `require` works but it throws an error on line 3.

**Comment by bendrucker** [comment]
We'll happily review a PR. This is a sufficiently rare use case that I doubt either Thorsten or I could make time for it.

**Comment by thlorenz** [comment]
This has nothing to do with proxyquire which just allows you to override what `require` returns.
You're asking to override an entirely different function that just happens to be attached to `require`.

So even a PR would stand low chances of being merged. Better create another module for that or simply do this:

### 1. Create module `require-resolve.js`:

```js
module.exports = require.resolve.bind(require)
```

### 2. Use it in your code i.e. in `get-plugin.js`

```js
var resolve = require('./require-resolve');
function getPlugin(pluginName){
    var plugin = require(pluginName);
    var pluginPath = resolve(pluginName); // ---> Error here

    return {
        api: plugin,
        path: pluginPath
    };
}
```

### 3. Override it in your tests

```js
var plugin = proxyquire('./get-plugin', { './require-resolve': function myresolve() { ... } });
```

**Comment by gyandeeps** [comment]
Awesome, thanks a lot @thlorenz . That helps a lot.

**Comment by thlorenz** [comment]
You're welcome.
Just as a note if your `require-resolve` needs to be fast then don't use `bind`, but this instead:

```js
module.exports = function requireResolve() { 
  require.resolve.apply(require, arguments) 
}
```

**Comment by thlorenz** [comment]
@gyandeeps since you like this so much how about adding a simple example to the [examples](https://github.com/thlorenz/proxyquire/tree/master/examples)/wrap or so?

We could point to it from the readme. Maybe we should also add an _Advanced Techniques_ section where we show these kind of things.
Thoughts @bendrucker? Could also go in the wiki and be linked from the Readme (from my experience people seldom find the wiki though).

**Comment by gyandeeps** [comment]
Will do that. Can you please assign this issue to me so that it comes up on my todo list.
fyi, I might take some time to get to this.
Thanks

**Comment by bendrucker** [comment]
I think it's fine to put it in the wiki and then link from the readme. The only difference between that and examples is that we'd merge a PR to examples whereas the wiki is public read/write.

**Comment by bendrucker** [comment]
Can't assign non-collabs to an issue, sorry

**Comment by thlorenz** [comment]
Adding @gyandeeps.
And in that case just creating a nice wiki page with Advanced Section showing the above example will suffice.
Still add this to the examples in the Readme as well (link it from wiki) so people can run it.

**Comment by thlorenz** [comment]
Don't reopen this. Your issue is solved.
If you need to track progress we can do so in the PR once you submit it.

**Comment by bendrucker** [comment]
> Does this approach have any obvious drawbacks that I'm not thinking of?

You're writing your source code with explicit test hooks in it. Proxyquire works best when you modularize your code well but it never asks you to touch every source file. I'm guessing you understood this though 😉 

If `foo` calls `require.resolve` on load instead of in some method your stubbing suggestion doesn't work. That's broadly true of `sinon` and why I avoid `sinon.stub(object, 'method')`. Mutating another module creates weird ordering dependencies and is hard to maintain.

You don't even need to call `resolve` on load—referencing it is enough. This breaks too:

```js
const resolve = require.resolve
// or const {resolve} = require

module.exports = {
  method: () => resolve('my-module')
}
```

This is a nice hack if it works for your circumstances though.

**Comment by macgyver** [comment]
The [caveat in your readme](https://github.com/thlorenz/proxyquire/#caveat) and this discussion inspired me to find a better solution that doesn't require hacking the node internals, thanks!
