### ISSUE TITLE
Support for ES 6 module syntax

### ISSUE THREAD

**Issue by kasajian** [thlorenz/proxyquire#88]
I think it would be useful to have something on the front page explaining to people how to use this in a browser if they are using ES6 modules, and not using browserify or nodejs/commonjs or amd

**Comment by bendrucker** [comment]
Proxyquire is Node only so we won't mention ES6 modules until it's natively supported

**Comment by ds82** [comment]
Maybe you could reconsider your opinion about es6 module syntax .. 

We write every bit of new code in es6 to make it future-proof. A lot of this code/modules can be used in nodejs and the browser. You are right, today it doesn't matter if I have to use require in my module code, because I have to transpile and package (browserify, webpack, ..) it for the browser anyway. But this probably changes in the future ... would be great to be able to use es6 module syntax _today_. 

I transpile my nodejs code anyway. The only reason for me not to use es6 module syntax in node is to be able to use proxquire ..

**Comment by thlorenz** [comment]
@ds82 Proxying `imports` is an entirely different story than proxying node.js's `require`.
I also believe that nodejs's implementation of the former is still very much in flux.
If you can get this working the same way though we are open to a PR to add this.

**Comment by jcrben** [comment]
Now that ES modules are available locally in 8.5 under the CLI flag `--experimental-modules` (see http://2ality.com/2017/09/native-esm-node.html), perhaps this should be revisited.

**Comment by thlorenz** [comment]
@jcrben if this is possible/what needs to be done is entirely dependent on how `import` plays together with require extensions.
In the ideal case in both the below cases proxyquire would work as before:

```js
const a = require('./a')
import './a' as a
```

You could help by running some experiments to see how much that is true.
I personally have no bandwidth at the moment to look into this nor will I use `import` in my node code for a long time to come (if only to not break older node versions).

**Comment by mreinstein** [comment]
have we surpassed the "for a long time to come" threshold? :-)
