### ISSUE TITLE
simultaneous usage of rewire and proxyquire

### ISSUE THREAD

**Issue by hellboy81** [thlorenz/proxyquire#90]
As I mentioned with `proxyquire` it is not possible  to access private variables on module level. It is only possible with `rewire`.

Conversely, `rewire` cannot stub `require` itself. I.e. all modules are loaded, although they should be stubbed and are not required installed for unit tests.

Is there possible to use both of this libraries simultaneously?

**Comment by bendrucker** [comment]
No idea. I believe that screwing with a separate file's scope via variable names is brittle and a bad idea. Regardless of the compatibility status I don't think Thorsten is cool with recommending rewire and I'm definitely not.

**Comment by XGHeaven** [comment]
@bendrucker I have an other problem. How to get and test private function or variable? Just export it??

**Comment by hellboy81** [comment]
+infinity

**Comment by XGHeaven** [comment]
@hellboy81 :question:

**Comment by hellboy81** [comment]
>How to get and test private function or variable?

use `rewire`, Luke!

**Comment by XGHeaven** [comment]
@hellboy81 Can't use `rewire` and `proxyquire` together. @bendrucker said...
:persevere:

**Comment by thlorenz** [comment]
The reason why proxyquire focuses on testing functions that are exported is that you should always test through the API that is exposed (except in very few edge cases).

So maybe you need to exercise that private function by calling a exposed one that uses it. If that's not easy enough then maybe that private function does a lot or the module containing it is too large.
The idea is that your tests should use the code the same way that your code (from outside of the module) is using it. Therefore use exposed functions only.

You may expose the private function or use rewire to call it (not recommended), but now your tests are calling code in that module differently then the rest of your app is which is not a good idea.

**Comment by hellboy81** [comment]
@XGHeaven I know

**Comment by hellboy81** [comment]
>You may expose the private function or use rewire to call it (**not recommended**), 

why?

**Comment by bendrucker** [comment]
The idea here is that you should be testing your public API. Coupling tests to internal variable names is equivalent to dropping breakpoints all over and then checking the scope. That's a useful tactic when something's wrong. For testing, it's likely to lead to tests that are tightly coupled to your source code. The result will be tests that break when you refactor even when the API is unchanged.

We're recommending breaking code into well-structured modules that expose an appropriate API. That might mean splitting a certain piece of functionality into two modules: one that does the lower level work, and one that composes the public API. The exact strategy depends on the project.

Proxyquire encourages thoughtful use of modules, while rewire will let you do whatever you want. I specifically won't use rewire because I want to be forced to structure modules appropriately and test the public APIs.

**Comment by brocoli** [comment]
This kind of one-size-fits-all opinion is honestly not very useful.

First of all, not all tests are made to be stable across changes. Unit tests of private functions are just that. If you refactor you usually throw those unit tests out and build them again with the new functions, no problem.

Depending on what you're working on and your team dynamics, this may be better than not covering these functions with unit tests, and relying only on what is effectively a number of integration tests to assert their correctness.

And the fact is that right now neither rewire nor proxyquire help that much. Rewire works after the module has already been required, so its dependencies have already been loaded and have already run who knows what code. Proxyquire on the other hand truly isolates my module from the rest of the application... but then we can't test private functions <_<

**Comment by bendrucker** [comment]
Locking this as I don't think additional commentary is helpful here
