### ISSUE TITLE
how does it play with babel and or ES6 import?

### ISSUE THREAD

**Issue by kilianc** [thlorenz/proxyquire#99]
Once the new module system lands in v8 without the `--harmony`, how do we proxyimport things?

**Comment by bendrucker** [comment]
Babel should work fine since it's just compiling to ES5 + CommonJS. As for native module support, we'll have to cross that bridge when we come to it. `import != require` and it may make sense to start entirely from scratch. That assumes that it's possible to implement a proxyquire equivalent in the first place. Since `import` is syntax and `require` is a special function, it might not be.

**Comment by kilianc** [comment]
@bendrucker thanks you nailed the answer :)

**Comment by chuckwilliams37** [comment]
Is it possible that the time to cross this bridge has come?  I'm working on a new project, learning ES6, and have no idea where to begin with this

**Comment by bendrucker** [comment]
No, until Node natively supports `import` proxyquire will need to change. As long as everyone's just transpiling there's no need. FWIW, I strongly recommend you not use `import` and instead stick to the ES6 features that are well-supported in Node.

**Comment by chuckwilliams37** [comment]
Thanks for the guidance!  I guess I'll write my firebase-related tests
without imports.

**Comment by uc2pac** [comment]
No natively supports import. Is it time now ))
